#{input.sfs_file} {output} {params.seq_len} {params.mut}
import sys
import os

sfs = sys.argv[1]
output = sys.argv[2]
seq_len = str(sys.argv[3])
mut_rate = str(sys.argv[4])

with open(sfs, "r") as f:
    sfs_values = f.readlines()[0]

blueprint = f"#file generated by prepare_stairway_blueprint.py \n\
popid: pop \n\
nseq: 20 \n\
L: {seq_len} \n\
whether_folded: false \n\
SFS: {sfs_values} \n\
pct_training: 0.67 \n\
nrand: 7	15	22	28 \n\
project_dir: pop \n\
stairway_plot_dir: stairway_plot_es \n\
ninput: 200 \n\
theta_upper_bound: 0.2 \n\
dimension_factor: 2000 \n\
mu: {mut_rate} \n\
year_per_generation: 1 \n\
plot_title: pop \n\
xrange: 0.1,10000000 \n\
yrange: 0,0 \n\
xspacing: 2 \n\
yspacing: 2 \n\
fontsize: 12 \n\
"
os.makedirs(output, exist_ok=True)

with open(f"{output}/model.blueprint", "w") as f:
    f.write(blueprint)

