import os
from distutils.util import strtobool

configfile: "snakemake/config.yml"

REPEATS = config["repeats"]
SFS_DIR = "snakemake/sfss"
PRED_DIR = "snakemake/prediction"
OUT_FILE=config["output_file"]
GRAPH=config["graph"],
BRANCH_SFS = bool(strtobool(str(config["branch_sfs"])))
BLOCKS = config["blocks"]
FIXED_TIMES = config.get("fixed_times", None)  # optional

if BRANCH_SFS:
    print("Using branch SFS")
    SCALE= 1 / (2*config["sequence_length"])  # scaling factor for mutation rate
else: 
    SCALE= config["mutation_rate"] # scaling factor for mutation rate
    print("Using site SFS (mutations)")

# Ensure output dirs exist
os.makedirs(SFS_DIR, exist_ok=True)
os.makedirs(PRED_DIR, exist_ok=True)

rule all:
    input:
        f"{OUT_FILE}_ci.png",
        f"{OUT_FILE}_ci_end_time.csv"

rule simulate_sfs:
    output:
        sfs_file = f"{SFS_DIR}/sfs_{{seed}}.blk"
    params:
        seq_len=config["sequence_length"],
        mut=config["mutation_rate"],
        rec=config["recombination_rate"]
    shell:
        "python snakemake/scripts/simulate_sfs.py {wildcards.seed} {GRAPH} {params.seq_len} {params.mut} {params.rec} {output.sfs_file} {BRANCH_SFS}"

rule plot_sfs:
    input:
        sfs_file = f"{SFS_DIR}/sfs_{{i}}.blk"
    output:
        directory(f"{PRED_DIR}/test{{i}}")
    params:
        seq_len=config["sequence_length"],
        mut=config["mutation_rate"],
        fixed_times=(f"-T {FIXED_TIMES}" if FIXED_TIMES is not None else "")

    shell:
        'bash blockbuster.sh --sfs {input.sfs_file} -p {output} -L {params.seq_len} -m {SCALE} {params.fixed_times} -l 1e-2'
        

rule anaylse:
    input:
        dirs = expand(f"{PRED_DIR}/test{{i}}", i=range(1, REPEATS + 1))
    output:
        yml = f"{OUT_FILE}.yml",
        png = f"{OUT_FILE}.png"
    shell:
        """
        python snakemake/scripts/combine.py {PRED_DIR} {BLOCKS} {output.yml}
        python snakemake/scripts/drawcombined.py {output.yml} {GRAPH} {output.png}
        """

rule confidence_interval:
    input:
        yml = f"{OUT_FILE}.yml",
        png = f"{OUT_FILE}.png"
    output:
        ci_yml = f"{OUT_FILE}_ci.png",
        csv = f"{OUT_FILE}_ci_end_time.csv"

    shell:
        "python snakemake/scripts/confidence_interval.py {OUT_FILE}.yml {GRAPH} {OUT_FILE}_ci.png"

#bash blockbuster.sh --sfs snakemake/sfss/sfs_1.blk -p test_new -L 23513712  -m 0.000000021 -P "0,0,0|0.4042631385520029,4.042631385520029"